add_newline = false

[aws]
disabled = true
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[directory]
style = "bright-cyan"
# truncate_to_repo = false

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
# prefix = "〈"
symbol = " "
style = "purple"

[git_commit]
style = "green"

[git_status]
# Fancy stuff that doesn't quite work because of
# icons/symbols that are wider than one character
# ahead = " 〉↑ "
# behind = " 〉↓ "
# conflicted =  " 〉 "
# deleted =  " 〉 "
# diverged = " 〉↑↓ "
# modified = " 〉ﱣ "
# modified = " 〉  "
# modified_count.enabled = true
# prefix = ""
# renamed = " 〉ﯽ "
# show_sync_count = true
# staged = " 〉 "
# stashed = " 〉ﭥ "
# stashed = "〉  "
# stashed_count.enabled = true
# style = "blue"
# suffix = " "
# untracked = " 〉 "

# Not-so-fancy stuff
ahead = "↑"
behind = "↓"
deleted = "✕"
diverged = "↑↓"
prefix = "❬"
style = "blue"
suffix = "❭ "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
