add_newline = false

[aws]
disabled = true
symbol = " "

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[conda]
symbol = " "

[directory]
style = "bright-cyan"
# truncate_to_repo = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
# prefix = "〈"
symbol = " "
# style = "purple"

[git_status]
# Not-so-fancy stuff
ahead = "↑${count}"
behind = "↓${count}"
deleted = "✕"
diverged = "↑${ahead_count}↓${behind_count}"
modified = "●"
style = "bold blue"
format = '([⟨$all_status$ahead_behind⟩]($style) )'

# Fancy stuff that doesn't quite work because of
# icons/symbols that are wider than one character
# ahead = " 〉↑ "
# behind = " 〉↓ "
# conflicted =  " 〉 "
# deleted =  " 〉 "
# diverged = " 〉↑↓ "
# modified = " 〉ﱣ "
# modified = " 〉  "
# modified_count.enabled = true
# prefix = ""
# renamed = " 〉ﯽ "
# show_sync_count = true
# staged = " 〉 "
# stashed = " 〉ﭥ "
# stashed = "〉  "
# stashed_count.enabled = true
# style = "blue"
# suffix = " "
# untracked = " 〉 "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
disabled = false

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[terraform]
disabled = true
