# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
# default-title = "{{format-date now 'timestamp'}} Untitled"
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
# filename = "{{id}}-{{slug title}}"
filename = "{{format-date now 'timestamp'}}_{{slug title}}"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"


# EXTRA VARIABLES
[extra]
author = "Jesper"

# group.fe_guild automatically matches the fe_guild directory
[group.fe_guild.note]
default-title = "Frontend Guild meeting"
template = "fe_guild.md"


# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"


# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"


# COMMAND ALIASES
[alias]

# Create Frontend Guild minutes
feg = 'zk new "$ZK_NOTEBOOK_DIR/fe_guild"'

# Edit the last modified note.
# edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
# lucky = "zk list --quiet --format full --sort random --limit 1"


# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
