-- Show tabs and spaces as characters
vim.opt.list = true
vim.opt.listchars:append("tab:│  ,lead:·,trail:·")

require("indent_blankline").setup({
	-- Default: ['class', 'function', 'method']
	-- context_patterns = {
	-- 	"^for",
	-- 	"^func",
	-- 	"^if",
	-- 	"^object",
	-- 	"^table",
	-- 	"argument_list",
	-- 	"arguments",
	-- 	"block",
	-- 	"catch_clause",
	-- 	"class",
	-- 	"dictionary",
	-- 	"do_block",
	-- 	"element",
	-- 	"else_clause",
	-- 	"except",
	-- 	"for",
	-- 	"function",
	-- 	"if_statement",
	-- 	"import_statement",
	-- 	"jsx_element",
	-- 	"jsx_self_closing_element",
	-- 	"labeled_statement",
	-- 	"method",
	-- 	"object",
	-- 	"return",
	-- 	"table",
	-- 	"try",
	-- 	"try_statement",
	-- 	"tuple",
	-- 	"typedef",
	-- 	"while",
	-- 	"with",
	-- },
	show_current_context = true,
	show_first_indent_level = false,
	space_char_blankline = " ",
	use_treesitter = true,
	use_treesitter_scope = true,
})
