set -U fish_color_normal normal;
set -U fish_color_command ffffff;
set -U fish_color_quote ffaf00;
set -U fish_color_redirection 00ffd7;
set -U fish_color_end 00d700;
set -U fish_color_param ff87ff;
set -U fish_color_selection c0c0c0;
set -U fish_color_search_match ffff00;
set -U fish_color_history_current normal;
set -U fish_color_operator 00a6b2;
set -U fish_color_escape 00a6b2;
set -U fish_color_cwd 008000;
set -U fish_color_cwd_root 800000;
set -U fish_color_valid_path normal;
set -U fish_color_autosuggestion bcbcbc;
set -U fish_color_user 00ff00;
set -U fish_color_host normal;
set -U fish_color_cancel normal;
set -U fish_pager_color_completion normal;
set -U fish_pager_color_description B3A06D yellow;
set -U fish_pager_color_prefix white --bold --underline;
set -U fish_pager_color_progress brwhite --background=cyan;
set -U fish_color_comment 6c6c6c;
set -U fish_color_error ff005f;
set -U fish_color_match normal;
